# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolink',
            name='qualtiy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
