# Generated by Django 2.0 on 2019-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20190521_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolink',
            name='quality',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
